// import { Poppins } from "next/font/google";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import "./globals.css";

import FooterSwitcher, { NavbarSwitcher } from "@/components/LayoutSwitcher";
import { Metadata } from "next";
import { Providers } from "@/components/providers";
import { avenirNext } from "@/lib/font";
import { ClarityProvider } from "../../ClarityProvider";

// Load fonts
// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
//   variable: '--font-poppins',
// })

export const metadata: Metadata = {
  title: "Neural Mind Atlas",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={`${avenirNext.variable} dark antialiased`}>
      <body>
        <GoogleAnalytics />
        <Providers>
          <NavbarSwitcher />
          {children}
          <ClarityProvider />
          <FooterSwitcher />
        </Providers>
      </body>
    </html>
  );
}