import "./style.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Neural Mind Atlas",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}